//DIO file 
//Author:Kirollos Gerges 
#ifndef DIO_H
#define DIO_H
#define INPUT_MODULE(DATA_DIRECTION_REGISTER,BIT_N)  DATA_DIRECTION_REGISTER&=(~(1<<BIT_N)); 
#define OUTPUT_MODULE(DATA_DIRECTION_REGISTER,BIT_N)  DATA_DIRECTION_REGISTER|=1<<BIT_N;  
#endif